name: learning_platform

services:
  postgres:
    image: postgres:16
    container_name: learning-pg
    restart: unless-stopped

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: learning_platform

    ports:
      - "5432:5432"
